Lebenslauf
ElenaGhn/cv pull request #2
Opened 2023-01-13 12:53 UTC by ElenaGhn

2023-01-14 14:46 UTC, n-g-devs requested changes

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +      <script>
bitte statt alert folgenden Ansatz verfolgen: https://getbootstrap.com/docs/5.0/components/modal/

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
jquery vom alten bootstrap -> weg

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
altes bootstrap -> weg

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +        .alert {
own style in diese hausübung nicht erlaubt -> remove

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +             will have the opportunity to use my creative and problem-solving skills.
entferne auskommentierten code

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +        <div class="alert alert-success alert-dismissable">
neuen Ansatz mit bootstrap modal verfolgen statt diesem alert

2023-01-14 14:46 UTC, n-g-devs commented on index.html
>           <br />
allgemein im ganzen file statt br mit margin arbeiten wenn du ein Abstand zwischen den Elementen haben willst

br ist eher dafuer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +           <li>Romanian: Mother language</li>
mother tongue!

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +          <a class="btn btn-outline-secondary mx-2" href="assets/Lebenslauf_Elena.pdf" target="_blank">Pdf Download</a>
Bitte hier modal Ansatz verwenden, wenn das für die Handy Ansicht ist, schau eher dass du dann beim modal mit der breite arbeitest statt den modal ein zweites mal reinzugeben, es kann sogar sein dass mit bootstrap5 die sich automatisch anpassen. ---> dev tool verwenden.

2023-01-14 14:46 UTC, n-g-devs commented on index.html
>            <p class=" bi bi-geo-fill"> &nbsp;Reumannplatz 1/12 1100, Vienna</p>
allgemein unnötige abstände löschen.

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +          class="bi bi-github  text-primary text-decoration-none" target="_blank">  &nbsp;
sinnlose abstände bitte überall checken

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +            <h2 class="accordion-header" id="headingOne">
ids und target namen: am besten einen ansprechenden Namen geben wie zB programmingSkillsHeading statt headingOne, und collapse programmingSkillsContent  (achtung wegen accordeon verhalten!!!!)

2023-01-14 14:46 UTC, n-g-devs commented on index.html
> +            })
falls du eigenen js oder css mal brauchst, waere es besser ein extra file zu machen

2023-01-14 14:46 UTC, n-g-devs commented on index.html
Bitte schauen dass die HTML indentation passt. -> reformat code

2023-01-14 14:46 UTC, n-g-devs commented on index.html
>            data-bs-toggle="offcanvas"
div zeile 32 ist nicht zu!

2023-01-15 14:47 UTC, ElenaGhn commented on index.html
> +          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
erledigt

2023-01-15 14:48 UTC, merged